import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "@/assets/css/globals.css";

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: "black",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export const metadata: Metadata = {
  title: "GennYoon Blog",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "min-h-screen bg-background font-sans antialiased",
          inter.className
        )}
      >
        <Header />
        <main className="flex justify-center">
          <div className="w-full md:w-[572px]">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
